Authors:
  type: entity
  table: authors
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: true
    email:
      type: string
      length: 255
      fixed: false
      nullable: true
    company:
      type: string
      length: 255
      fixed: false
      nullable: true
    companyUrl:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: company_url
  lifecycleCallbacks: {  }
