ExtReferences:
  type: entity
  table: ext_references
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    vulnerabilityId:
      type: integer
      unsigned: false
      nullable: false
      column: vulnerability_id
    extReferenceTypeId:
      type: integer
      unsigned: false
      nullable: true
      column: ext_reference_type_id
    value:
      type: text
      nullable: true
    indirect:
      type: boolean
      nullable: true
    fourofour:
      type: boolean
      nullable: true
  lifecycleCallbacks: {  }
