Vcert\VeilleBundle\Entity\Credits:
  type: entity
  table: credits
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    vulnerabilityId:
      type: integer
      unsigned: false
      nullable: true
      column: vulnerability_id
    authorId:
      type: integer
      unsigned: false
      nullable: true
      column: author_id
  lifecycleCallbacks: {  }
