Vcert\VeilleBundle\Entity\Exploitdb:
  type: entity
  table: exploitdb
  fields:
    id:
      id: true
      type: string
      length: 11
      fixed: false
      nullable: false
    titre:
      type: text
      nullable: false
    auteur:
      type: text
      nullable: true
    pubdate:
      type: text
      nullable: true
    lien:
      type: text
      nullable: false
    guid:
      type: text
      nullable: true
  lifecycleCallbacks: {  }
