Vcert\VeilleBundle\Entity\ExtReferenceTypes:
  type: entity
  table: ext_reference_types
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
