Vcert\VeilleBundle\Entity\Oval:
  type: entity
  table: oval
  fields:
    id:
      id: true
      type: string
      length: 11
      fixed: false
      nullable: false
    titre:
      type: text
      nullable: false
    description:
      type: text
      nullable: true
    pubdate:
      type: datetime
      nullable: true
    lien:
      type: text
      nullable: false
    category:
      type: text
      nullable: true
    guid:
      type: text
      nullable: true
  lifecycleCallbacks: {  }
